### PR TITLE
Use React to display inline forms

### PR DESCRIPTION
**Pull request by graysonwright**
React is more flexible than `best_in_place`.
We'll have better control over the style of the app,
and we'll be able to group multiple fields into a single form.

- https://trello.com/c/R8Iaw1JJ
- https://facebook.github.io/react/

### CODE REVIEW

**Comment by graysonwright** [comment]
- [ ] Confirm before deleting URLs
- [ ] JS Tests

**Comment by MichaelTSS** [comment]
@graysonwright is there a reason you don't minify `es5-shim.js`?
When can I test this?

**Comment by graysonwright** [comment]
Michael - Rails will process `es5-shim` before it serves it. In development, it doesn't minify it. In production, it does.

**Comment by MichaelTSS** [comment]
ok thanks!

**Comment by graysonwright** [comment]
If you check out this branch (`react`), you should be able to get it running locally. You'll probably have to do a `bundle install` again.

Let me know what you think of using React - if you have alternatives that you'd prefer, let me know.

**Comment by MichaelTSS** [comment]
I'd never used React so I wouldn't know. What do you think of it?

**Comment by graysonwright** [comment]
I really like React, but I don't want to introduce something that will be difficult to get up-to-speed with.

Check out the examples here: http://facebook.github.io/react/

If you have an hour or two, there's a great tutorial there (http://facebook.github.io/react/docs/tutorial.html) that should get you pretty comfortable with it.

**Comment by MichaelTSS** [comment]
sounds good thanks!

**Comment by graysonwright** [comment]
Closing in favor of https://github.com/sfbrigade/ohana-api/pull/17

**Pull request closed without merging**
